deploy:
  global:
    project_name: "app"
    clusterName: "grpc-service"
    image:
      repository: "edwynrrangel/grpc-server"
      tag: "latest"
      pullPolicy: Always
    imagePullSecrets: 
      name: "dockerhub"
    namespace: "default"
  helm:
    chart: "edwynrrangel/grpc-server"
    chartVersion: "0.1.0"
