deploy:
  global:
    project_name: "app"
    clusterName: "grpc-service"
    image:
      repository: "edwynrrangel/grpc-server"
      tag: "latest"
      pull_policy: Always
    image_pull_secrets: 
      - name: "dockerhub"
    namespace: "default"
  helm:
    chart: "edwynrrangel/grpc-server"
    chart_version: "0.1.0"
