global:
  enabled: true
  projectName: "#{DEPLOY_PROJECT_NAME}#"
  clusterName: "#{DEPLOY_CLUSTER_NAME}#"

  # Configuración de la imagen Docker de la aplicación
  image:
    repository: "#{DEPLOY_IMAGE_REPOSITORY}#"
    tag: "#{DEPLOY_IMAGE_TAG}#"
    pullPolicy: "#{DEPLOY_IMAGE_PULL_POLICY}#"
  imagePullSecrets: 
    - name: "#{DEPLOY_IMAGE_PULL_SECRETS}#"
  namespace: "#{DEPLOY_NAMESPACE}#"

app:
  enabled: true
  replicaCount: 1

  # Configuraciones de recursos para el pod (CPU, memoria)
  resources:
    requests:
      memory: "200Mi"
      cpu: "75m"
    limits:
      memory: "512Mi"
      cpu: "1000m"

  # Configuraciones del servicio de Kubernetes
  service:
    type: ClusterIP
    port: 50051

  # Configuraciones de sondeos de liveness y readiness
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    # Configuración específica para gRPC o HTTP

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    # Configuración específica para gRPC o HTTP

  # Configuraciones de autoscaling para el despliegue
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  # Configuraciones de seguridad, como contextos de seguridad del pod
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
