name: Deploy Go

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables from YAML
        uses: edwynrrangel/github-actions-suite/actions/yaml-to-env@master
        with:
          yaml-file: k8s/config.yaml
      
      - name: Print environment variables
        run: |
          echo "ENVIRONMENT VARIABLES"
          echo "namespace=$DEPLOY_NAMESPACE"
        
      