name: Test yaml-to-env

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables from YAML
        uses: edwynrrangel/github-actions-suite/actions/yaml-to-env@master
        with:
          yaml-file: k8s/config.yaml
      
      - name: Debug GITHUB_ENV
        run: cat $GITHUB_ENV
      
      - name: Replace tokens in YAML
        uses: edwynrrangel/github-actions-suite/actions/replace-tokens@master
        with:
          input-yaml-file: k8s/values.yaml
      